"""empty message

Revision ID: 10bc41d3f796
Revises: 39c58e024d94
Create Date: 2024-03-21 15:07:21.731484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bc41d3f796'
down_revision = '39c58e024d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.String(length=250), nullable=True))
        batch_op.drop_constraint('favorites_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_homeworld_id_fkey', 'planets', ['homeworld_id'], ['id'])
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###
