"""empty message

Revision ID: 33f57b3534d5
Revises: 354be52feb38
Create Date: 2024-03-18 19:31:30.898152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f57b3534d5'
down_revision = '354be52feb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('characters_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('characters_homeworld_fkey', 'planets', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
