"""empty message

Revision ID: 354be52feb38
Revises: 97948d233c07
Create Date: 2024-03-18 19:25:29.296510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354be52feb38'
down_revision = '97948d233c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['homeworld'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_residents_fkey', type_='foreignkey')
        batch_op.drop_column('residents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residents', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planets_residents_fkey', 'characters', ['residents'], ['id'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###
