"""empty message

Revision ID: 5d9a91a5742e
Revises: efe2b5bf1cb8
Create Date: 2024-03-20 03:52:31.883432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9a91a5742e'
down_revision = 'efe2b5bf1cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_char_id_fkey', type_='foreignkey')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_char_id_fkey', 'characters', ['char_id'], ['id'])

    # ### end Alembic commands ###
